* Stefan H Sold's Blog
** About Me
*** Vita
| Timestamp  | Event               | How I felt about it    |
|------------+---------------------+------------------------|
| 1991-08-?? | First day in school | excited                |
| 1986-03-22 | Birth               | energized and stressed |

** Music Stuff

* Fluxbox
Yes, it's old but I love it! Write about the features you like ...
** Compile it yourself
I found that the debian package of fluxbox (which version?) does not support (or
it simply doesn't work do to a bug?) the great autotiling function 'arrangewindows'.
Here, fluxbox guesses the 'best' arrangement compared to other other options
like arrangewindowshorizontal or arrangewindowsstackright where the user already
imposes a structure. So I decided
to compile the newest version (1.3.7) myself. Of course I want to build a
package first to make a clean install and (if necessary) deinstall possible. So
I use the debian trinity of binary package building
#+NAME: fluxbox_build
#+BEGIN_SRC bash
./configure
dh_make --createorig
fakeroot debian/rules binary
#+END_SRC
with the default settings. Afterwards I installed it with
#+BEGIN_SRC bash
dpkg --install 'the_package'
#+END_SRC
(root privileges). What I did not know was that the default config settings do
not include xinerama, imlib2 (for png image support), and freetype fonts.
Eventually, I ended up with a fullscreen stretched over two monitors, all icons
disappeared in my menu, and this default fluxbox font with an appearance that
only a mother can like. If you type './configure --help' it reads
#+BEGIN_SRC bash
[...]
  --disable-imlib2        disable imlib2 support
  --disable-xft           disable xft support
  --disable-freetype2     disable freetype2 support
  --disable-xrender       disable xrender support
  --disable-xpm           disable xpm support
  --disable-xinerama      disable xinerama support
[...]
#+END_SRC
so I thought I is activated by default and you only can deactivate it. However,
the config didn't take it into account, obviously. What I hadn't read just a few
lines above is the following
#+BEGIN_SRC bash
  --disable-option-checking  ignore unrecognized --enable/--with options
  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
#+END_SRC
I gave it a try with '--enable-imlib2' etc. and look here the config was
complaining
#+BEGIN_SRC bash
checking for  imlib2 >= 1.0.0 ... no
configure: error: *** imlib2 support requested but libraries not found
#+END_SRC

If you try --enable-text the option is unrecognized, however!

I configured it with
#+BEGIN_SRC bash
./configure --enable-slit --enable-xmb --enable-imlib2 \
--enable-xrender --enable-freetype2 --enable-xpm \
--enable-xrandr --enable-xft --enable-text
#+END_SRC

I had trouble with xft. Although, config didn't show any errors, the packege
build process 

Questions:
What is:
+ xmb
+ xpm
+ xft
+ text

For a successful config I had to install the following packages:
+ libimlib2-dev
+ libxfg-dev
+ libxpm-dev
+ libxrandr-dev

Doing the [[file+emacs:index.org::fluxbox_build][Fluxbox Build]] now gives me an error that it cannot follow references.
At that point I gave up the debian way and tried the ubuntu way with checkinstall.
So I did the ubuntu package build
#+NAME: ubuntu_fluxbox_build
#+BEGIN_SRC bash
./configure --enable-slit --enable-xmb --enable-imlib2 \
--enable-xrender --enable-freetype2 --enable-xpm \
--enable-xrandr --enable-xft --enable-text
make
checkinstall
#+END_SRC
checkinstall without sudo such that I can install it with dpkg after I
deinstalled the old fluxbox version.  This worked super fast, without any
errors, and gave me the result is exactly what I wanted.  I don't know what went
wrong with the debian method. I guess I did something horrobly wrong.

** Integrate it yourself such that the Desktop Manager can find it
My DIY deb package didn't take care of the Desktop Manager (DM) integration of fluxbox. So I had
to do this manually which isn't that hard once you know the location where the
DM is looking for. The folder of subject is /usr/share/xsessions, here you
should find some *.desktop files and I put the fluxbox.desktop here with the
following content
#+BEGIN_SRC bash
[Desktop Entry]
Name=fluxbox
Comment=This session logs you into fluxbox
Exec=/usr/bin/startfluxbox
TryExec=/usr/bin/fluxbox
Type=Application
DesktopNames=fluxbox
X-GDM-SessionRegisters=true

[X-Window Manager]
SessionManaged=true
#+END_SRC
'TryExec' is questionable as well as 'X-GDM-SessionRegisters=true'. The latter
one is just copy-pasted from a gnome.desktop file I used as a template. For the
former one: I put 'fluxbox' instead of 'startfluxbox' since I thought it's a
fallback and so I put something different to the usual 'Exec'. This might be
completely wrong. 

I should mention that although I had the Gnome ecosystem installed I switched to
lightdm (update-alternatives).

Anyhow, the your DM should now be able to find fluxbox and lists it in the
session drop-down menu.

* Emacs

* My secret interest for Warhammer
I first met Warhammer when I was a freshman at the university
